-- ─────────────────────────────────────────────────────────────────────────────
-- Supabase Migration: Initial Schema
-- Run this in: Supabase Dashboard → SQL Editor → New Query → Run
-- Or via: supabase db push (if using Supabase CLI)
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: news_items
-- Stores fetched news articles and GitHub repos per day.
-- status flow: pending → approved | rejected → tweeted
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS news_items (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    date         DATE        NOT NULL,
    title        TEXT        NOT NULL,
    url          TEXT        NOT NULL,
    url_hash     TEXT        GENERATED ALWAYS AS (md5(url)) STORED,
    source       TEXT        NOT NULL,                           -- e.g. "TechCrunch", "GitHub Trending"
    category     TEXT        NOT NULL DEFAULT 'general'          -- ai | github | latam | saas | general
                             CHECK (category IN ('ai', 'github', 'latam', 'saas', 'general')),
    summary      TEXT,
    image_url    TEXT,
    status       TEXT        NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('pending', 'approved', 'rejected', 'tweeted')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    approved_at  TIMESTAMPTZ
);

-- Prevent duplicate URLs within the same day
CREATE UNIQUE INDEX IF NOT EXISTS news_items_date_url_hash_idx
    ON news_items (date, url_hash);

-- Speed up common queries
CREATE INDEX IF NOT EXISTS news_items_date_idx    ON news_items (date DESC);
CREATE INDEX IF NOT EXISTS news_items_status_idx  ON news_items (status);
CREATE INDEX IF NOT EXISTS news_items_category_idx ON news_items (category);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: tweets
-- Stores tweet threads generated by OpenClaw Agent 2.
-- content is an array of tweet texts (max 5 items = max 5-tweet thread).
-- status flow: draft → scheduled → posted | failed
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tweets (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    news_id      UUID        NOT NULL REFERENCES news_items(id) ON DELETE CASCADE,
    content      TEXT[]      NOT NULL,                           -- array of tweet texts, [0] = first tweet
    scheduled_at TIMESTAMPTZ,                                   -- when to post (set by OpenClaw Agent 2)
    posted_at    TIMESTAMPTZ,
    x_tweet_id   TEXT,                                          -- Twitter/X tweet ID of the first tweet in thread
    x_thread_ids TEXT[],                                        -- all tweet IDs in the thread
    status       TEXT        NOT NULL DEFAULT 'draft'
                             CHECK (status IN ('draft', 'scheduled', 'posted', 'failed')),
    error_msg    TEXT,                                          -- populated if status = 'failed'
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS tweets_status_idx        ON tweets (status);
CREATE INDEX IF NOT EXISTS tweets_scheduled_at_idx  ON tweets (scheduled_at);
CREATE INDEX IF NOT EXISTS tweets_news_id_idx       ON tweets (news_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- The backend uses service_role key (bypasses RLS).
-- Keeping RLS enabled is good practice; anon key will be blocked.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE news_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE tweets     ENABLE ROW LEVEL SECURITY;

-- Allow full access only to the service_role (backend server)
CREATE POLICY "service_role full access on news_items"
    ON news_items FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "service_role full access on tweets"
    ON tweets FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- HELPER: auto-set approved_at when status flips to 'approved'
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_approved_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status = 'approved' AND OLD.status != 'approved' THEN
        NEW.approved_at = NOW();
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_news_items_approved_at
    BEFORE UPDATE ON news_items
    FOR EACH ROW EXECUTE FUNCTION set_approved_at();
