"""
backend/routes/tweets.py
Tweet scheduling endpoints:
  POST  /api/tweets/schedule          — save a generated tweet thread (from OpenClaw Agent 2)
  GET   /api/tweets/pending           — get scheduled tweets not yet posted (for tweet_poster.py)
  PATCH /api/tweets/{id}/posted       — mark a tweet as successfully posted
  PATCH /api/tweets/{id}/failed       — mark a tweet as failed with error message
  GET   /api/tweets                   — list all tweets for a date (for dashboard display)
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, HTTPException, Query

from backend.database import get_supabase
from backend.models import TweetOut, TweetPostedPatch, TweetScheduleRequest

router = APIRouter(prefix="/api/tweets", tags=["tweets"])


@router.post("/schedule", response_model=TweetOut)
def schedule_tweet(payload: TweetScheduleRequest):
    """
    Save a tweet thread generated by OpenClaw Agent 2.
    content is a list of tweet strings (max 5 = full thread).
    """
    if not payload.content:
        raise HTTPException(status_code=400, detail="content array cannot be empty")
    if len(payload.content) > 5:
        raise HTTPException(status_code=400, detail="Thread cannot exceed 5 tweets")

    sb = get_supabase()

    # Verify the news item exists
    news_res = sb.table("news_items").select("id").eq("id", str(payload.news_id)).execute()
    if not news_res.data:
        raise HTTPException(status_code=404, detail="news_id not found")

    row = {
        "news_id": str(payload.news_id),
        "content": payload.content,
        "scheduled_at": payload.scheduled_at.isoformat() if payload.scheduled_at else None,
        "status": "scheduled" if payload.scheduled_at else "draft",
    }
    res = sb.table("tweets").insert(row).execute()
    if not res.data:
        raise HTTPException(status_code=500, detail="Failed to save tweet")
    return res.data[0]


@router.get("/pending", response_model=list[TweetOut])
def get_pending():
    """
    Return tweets that are scheduled and ready to post (scheduled_at <= now).
    Called by tweet_poster.py cron script.
    """
    sb = get_supabase()
    now = datetime.now(timezone.utc).isoformat()
    res = (
        sb.table("tweets")
        .select("*")
        .eq("status", "scheduled")
        .lte("scheduled_at", now)
        .order("scheduled_at", desc=False)
        .execute()
    )
    return res.data


@router.get("", response_model=list[TweetOut])
def list_tweets(
    date_str: Optional[str] = Query(None, alias="date", description="YYYY-MM-DD, defaults to today"),
):
    """List all tweets for a given day (joined through news_id date)."""
    from datetime import date as date_type
    target_date = date_str or date_type.today().isoformat()
    sb = get_supabase()

    # Get news item IDs for this date first
    news_res = (
        sb.table("news_items")
        .select("id")
        .eq("date", target_date)
        .execute()
    )
    news_ids = [row["id"] for row in news_res.data]
    if not news_ids:
        return []

    res = (
        sb.table("tweets")
        .select("*")
        .in_("news_id", news_ids)
        .order("scheduled_at", desc=False)
        .execute()
    )
    return res.data


@router.patch("/{tweet_id}/posted", response_model=TweetOut)
def mark_posted(tweet_id: UUID, patch: TweetPostedPatch):
    """Mark a tweet thread as successfully posted. Called by tweet_poster.py."""
    sb = get_supabase()
    posted_at = (patch.posted_at or datetime.now(timezone.utc)).isoformat()
    update = {
        "status": "posted",
        "x_tweet_id": patch.x_tweet_id,
        "x_thread_ids": patch.x_thread_ids,
        "posted_at": posted_at,
    }
    res = (
        sb.table("tweets")
        .update(update)
        .eq("id", str(tweet_id))
        .execute()
    )
    if not res.data:
        raise HTTPException(status_code=404, detail="Tweet not found")

    # Also mark the related news item as tweeted
    news_id = res.data[0]["news_id"]
    sb.table("news_items").update({"status": "tweeted"}).eq("id", news_id).execute()

    return res.data[0]


@router.patch("/{tweet_id}/failed", response_model=TweetOut)
def mark_failed(tweet_id: UUID, error_msg: str = Query(...)):
    """Mark a tweet as failed. Called by tweet_poster.py on X API error."""
    sb = get_supabase()
    res = (
        sb.table("tweets")
        .update({"status": "failed", "error_msg": error_msg})
        .eq("id", str(tweet_id))
        .execute()
    )
    if not res.data:
        raise HTTPException(status_code=404, detail="Tweet not found")
    return res.data[0]
